{% set name = "robotframework" %}
{% set version = "4.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
    sha256: 93c2107f789fd897f234f4b8f1ba8e7b9f4ef326d9bcbfceb71dda8cc197388c
    folder: dist
  - url: https://github.com/robotframework/robotframework/archive/v{{ version }}.tar.gz
    sha256: adae7e4cb9a8a279eae42c72775d5f7d49f0bbd061d4215d5e9d6cfee370df28
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robot = robot.run:run_cli
    - rebot = robot.rebot:rebot_cli
    - libdoc = robot.libdoc:libdoc_cli

requirements:
  host:
    - pip
    - python >=2.7,<3|>=3.5
  run:
    - python >=2.7,<3|>=3.5

test:
  requires:
    - docutils
    - enum34  # [py<35]
    - jsonschema
    - lxml
    - pillow
    - pygments
    - pyyaml
  source_files:
    - src/utest
    - src/atest
    - src/doc/schema
    - src/README.rst
  imports:
    - robot
    - robot.api
    - robot.conf
    - robot.htmldata
    - robot.libdocpkg
    - robot.libraries
    - robot.model
    - robot.output
    - robot.output.console
    - robot.parsing
    - robot.reporting
    - robot.result
    - robot.running
    - robot.running.arguments
    - robot.running.timeouts
    - robot.utils
    - robot.variables
  commands:
    - robot --version
    - rebot --version

about:
  home: http://robotframework.org
  license: Apache-2.0
  license_file: dist/LICENSE.txt
  summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
  doc_url: http://robotframework.org/robotframework/{{ version }}/RobotFrameworkUserGuide.html
  dev_url: https://github.com/robotframework/robotframework
  description: >
    Robot Framework is a generic open source automation framework for acceptance testing, acceptance test driven development (ATDD), and robotic process automation (RPA). It has simple plain text syntax and it can be extended easily with libraries implemented using Python or Java.

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
    - alexvds
    - bollwyvl
