{% set name = "robotframework" %}
{% set version = "3.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
    sha256: d693e6d06b17f48669e2a8c4cb6c1f0d56e5f1a74835d18b8ea2118da7bf2d79
    folder: dist
  - url: https://github.com/robotframework/robotframework/archive/v{{ version }}.tar.gz
    sha256: 9805faa0990125ff2c9689b673448d5f47e78470e7a8e95af1606a775fa8379f
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robot = robot.run:run_cli
    - rebot = robot.rebot:rebot_cli

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - docutils
    - enum34  # [py<35]
    - lxml
    - pillow
    - pygments
    - pyyaml
  source_files:
    - src/utest
    - src/atest
    - src/README.rst
  imports:
    - robot
    - robot.api
    - robot.conf
    - robot.htmldata
    - robot.libdocpkg
    - robot.libraries
    - robot.model
    - robot.output
    - robot.output.console
    - robot.parsing
    - robot.reporting
    - robot.result
    - robot.running
    - robot.running.arguments
    - robot.running.timeouts
    - robot.utils
    - robot.variables
  commands:
    - robot --version
    - rebot --version

about:
  home: http://robotframework.org
  license: Apache-2.0
  license_file: dist/LICENSE.txt
  summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
  doc_url: http://robotframework.org/robotframework/{{ version }}/RobotFrameworkUserGuide.html
  dev_url: https://github.com/robotframework/robotframework
  description: >
    Robot Framework is a generic open source automation framework for acceptance testing, acceptance test driven development (ATDD), and robotic process automation (RPA). It has simple plain text syntax and it can be extended easily with libraries implemented using Python or Java.

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
    - alexvds
    - bollwyvl
