{% set version = "5.0.1" %}

package:
  name: robotframework
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/r/robotframework/robotframework-{{ version }}.zip
    sha256: cf5dc59777ed9d8c3e1e91fb4403454890242867735681f22f4f22dbb2a20fc8
    folder: dist
  - url: https://github.com/robotframework/robotframework/archive/v{{ version }}.tar.gz
    sha256: 93a9a7504738d7493994c3a7f4f13b4591beb746a26cb141afdb0435909b9c81
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robot = robot.run:run_cli
    - rebot = robot.rebot:rebot_cli
    - libdoc = robot.libdoc:libdoc_cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - docutils
    - enum34  # [py<35]
    - jsonschema
    - lxml
    - pillow
    - pygments
    - pyyaml
  source_files:
    - src/utest
    - src/atest
    - src/doc/schema
    - src/README.rst
  imports:
    - robot
    - robot.api
    - robot.conf
    - robot.htmldata
    - robot.libdocpkg
    - robot.libraries
    - robot.model
    - robot.output
    - robot.output.console
    - robot.parsing
    - robot.reporting
    - robot.result
    - robot.running
    - robot.running.arguments
    - robot.running.timeouts
    - robot.utils
    - robot.variables
  commands:
    - robot --version
    - rebot --version

about:
  home: http://robotframework.org
  license: Apache-2.0
  license_file:
    - dist/LICENSE.txt
    - dist/COPYRIGHT.txt
  summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
  doc_url: http://robotframework.org/robotframework/{{ version }}/RobotFrameworkUserGuide.html
  dev_url: https://github.com/robotframework/robotframework
  description: >
    Robot Framework is a generic open source automation framework for acceptance testing, acceptance test driven development (ATDD), and robotic process automation (RPA). It has simple plain text syntax and it can be extended easily with libraries implemented using Python or Java.

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
