{% set name = "robotframework" %}
{% set version = "4.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
    sha256: efd39558219fddc86473d4d390aeaec60640d7a7567a15fd51c0576f20e46171
    folder: dist
  - url: https://github.com/robotframework/robotframework/archive/v{{ version }}.tar.gz
    sha256: 4eb9965fb36dca36e8e2388c75990fecfc1347705cdb66b7a3a75181949edf42
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robot = robot.run:run_cli
    - rebot = robot.rebot:rebot_cli
    - libdoc = robot.libdoc:libdoc_cli

requirements:
  host:
    - pip
    - python >=2.7,<3|>=3.5
  run:
    - python >=2.7,<3|>=3.5

test:
  requires:
    - docutils
    - enum34  # [py<35]
    - jsonschema
    - lxml
    - pillow
    - pygments
    - pyyaml
  source_files:
    - src/utest
    - src/atest
    - src/doc/schema
    - src/README.rst
  imports:
    - robot
    - robot.api
    - robot.conf
    - robot.htmldata
    - robot.libdocpkg
    - robot.libraries
    - robot.model
    - robot.output
    - robot.output.console
    - robot.parsing
    - robot.reporting
    - robot.result
    - robot.running
    - robot.running.arguments
    - robot.running.timeouts
    - robot.utils
    - robot.variables
  commands:
    - robot --version
    - rebot --version

about:
  home: http://robotframework.org
  license: Apache-2.0
  license_file: dist/LICENSE.txt
  summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
  doc_url: http://robotframework.org/robotframework/{{ version }}/RobotFrameworkUserGuide.html
  dev_url: https://github.com/robotframework/robotframework
  description: >
    Robot Framework is a generic open source automation framework for acceptance testing, acceptance test driven development (ATDD), and robotic process automation (RPA). It has simple plain text syntax and it can be extended easily with libraries implemented using Python or Java.

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
    - alexvds
    - bollwyvl
