travis:
  secure:
    BINSTAR_TOKEN: U6xLUtPXI/QBDTmhUxVcERV0Ch8p1qkICrbx6BX+a46ycCzRRRr3Xm7jdg/WhOmw+gWQ1cJRDuw+8H8o/tf/xf8zdxek5qoZ9mcOWezv/OYEasnzl0Y7JqCIAcSLOxX67GtYCA8EOWYeo7PG6OLpv/4FdSAz2k1O2Bo1/r16pbsBokYZO6gv2unTC7U6cKEcWLCVCcy6cVahcazQbv2wxE5XD1ErUTV08vHRyHkkYthIIUTjzr4WutZgKDmhw5TvjrGXSiMnJlJVBvaUHxZWgROjJZD31kjawpBLqd/krZmXkJr5Y6p93jIJBEQISx2T1eWZA3sopgX02UdmulwJ+XsSdkcUtmDaMrSVOh9JHJGZctEKxImnP9hetxS5GGhNWjIqvMMP4tsLDRMJboTIZc0xdz2UW2y7FClVxmyjy3qjhwgROqasFlZlY2/00PUhzz65CSJSxQfvhrzdpsvjqLJw+reZrYIovrKbhEsOKGxaCu2pnwsbWqYIYmHSlZ2O0lc0PkYG3ZtiFc0xgx5+EhRqjBYW0HeJmXwFk2niqVm7VcfswPpL9aW3mMk7hUNLCpKwo/x2pVPterjspXD+NTAOaZO1SftLuPVstQzIQCugiIWYVV63kr+iaKMjmYR/YgMJjyPq8Q3vk1U72DYi0fFTn8ZEY1mi4p0oVM+oeAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
