travis:
  secure:
    BINSTAR_TOKEN: UwhRaND2TFy3CIf3DIis8+3qzPbZo2JGY2Hxe5C9ZHvLXL7rcqYpzFwtKDn9fM6PovIQMzyne7DYoo9vUeGAcwYGHrLFcSwMRReQOBR+bTmlZdao7AfD802SCvfrV/Q6yaKaeNjN9h0giUAw8zL2aBq4tcH8K4aSibOTLtIn6/0NfF6qt9ofMgGWiwWC5ukaB0qoP+zWz1dSUWHtiO7J4o95mFSSkAsUorSF8PCBlo/V8wBE9gsoxyOD1dUz6NVcvLxhab6v7EIbiwW2ej8NgPVA87f8RE/hrNdJsiO8eAA9RYhCWMxepnjZcyFwrG5XFwFjszcFdQkiZgtRmjCdObe7r/FwJZ52BZEk6JefbuwpehbFUO7airsOvjB+2xM92shEY56mrNW4ETYu23HKol92eDNcPV2K69dXEx5GVDJJc9+YEt07VJ5tNYHUcMz8ZO6Bi/m47IeL92L8cGKujSidF4zi+/gmpdy7c4EHiAp/jnGnQCiOb6HfofqFOiwfFFxVvR2tt4/jZEMp/pb06nEIFUKRh6aOq5wcr9t1MmujLoTnN2fIKU44Ig+nXt2okSTz5XmnRR5LprHnGTtJibKUcaUBVsBndJlACK9JCW+Vu34XdyYJhkFo0DYi4u5x9IR/LRM6FP90XfJZJJutW/HMKOzT25GqHzneBkawX/4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
